apiVersion: v1
kind: Service

metadata:
  name: statistics
  namespace: devops-lab

spec:
  type: ClusterIP

  selector:
    app: statistics

  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000