# Generated by Django 5.2 on 2025-11-23 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membershiptype',
            name='duration',
        ),
        migrations.AddField(
            model_name='membershiptype',
            name='description',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
    ]
