# Generated by Django 5.2 on 2025-11-23 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0004_workoutsession_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membership',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='user',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='workoutsession',
            name='owner',
        ),
    ]
