# Generated by Django 5.2 on 2025-11-23 11:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0005_remove_membership_owner_remove_user_owner_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='memberships_created', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь (владелец записи)'),
        ),
    ]
