# Generated by Django 5.2 on 2025-11-29 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0007_user_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('client', 'Клиент'), ('trainer', 'Тренер'), ('admin', 'Администратор')], max_length=16, verbose_name='Роль'),
        ),
    ]
