# Generated by Django 5.2.6 on 2025-12-07 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0008_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='totp_key',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='TOTP-ключ'),
        ),
    ]
