# Generated by Django 5.2.6 on 2026-09-05 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0009_user_totp_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='totp_key',
        ),
    ]
